name: Build

on: [push, pull_request]

jobs:
  install:

    strategy:
      matrix:
        os: [ macos-10.15 ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Copy formulae
      run: cp *.rb $(brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/
    - name: Install
      # We install the IIO Oscilloscope package, which builds the others
      # through dependency resolution.
      run: brew install --verbose --build-from-source iio-oscilloscope
    - name: Test
      run: |
        for formula in *.rb; do
          brew test "${formula%.rb}"
        done
